image: conan-cpp:latest

# We need to get the full history so we can automatically generate a version:
variables:
  GIT_DEPTH: "0"

stages:
  - init
  - build
  - test
  - build_and_upload_image
  - deploy_tst

init:
  stage: init
  script:
    - conan profile detect || echo "Profile already exists, continuing..."
    - sed -i 's/compiler.cppstd=gnu17/compiler.cppstd=17/' ~/.conan2/profiles/default
    - if ! conan remote list | grep -q "conan-hosted"; then
        conan remote add conan-hosted http://nexus.local:8081/repository/conan-hosted/ --insecure;
      else
        echo "Remote conan-hosted already exists, skipping add";
      fi
    - conan remote login conan-hosted conan-upload -p "Abcd1234!"
    - echo "VERSION=$(./get-version.sh)" > build.env
  artifacts:
    reports:
      dotenv: build.env
  
build:
  stage: build
  script:
    - conan build . --build=missing
  artifacts:
    paths:
      - build/Release/unit_tests
      - build/Release/fibonacci-webservice

test:
  stage: test
  script:
    - build/Release/unit_tests --gtest_output=xml:build/test-results.xml
  artifacts:
    reports:
      junit: build/test-results.xml

build_and_upload_image:
  stage: build_and_upload_image
  script:
    - ./build-image.sh
  only:
    - main

deploy_tst:
  stage: deploy_tst
  environment: tst
  image: ansible:latest
  script:
    - ./deploy-to.sh tst $VERSION
  only:
    - main
