---
- name: Deploy Fibonacci Webservice with Docker
  hosts: all
  vars:
    webservice_host_port: 27372
  tasks:
    - name: Start fibonacci-webservice container
      community.docker.docker_container:
        name: fibonacci-webservice
        # fibonacci_webservice_version should be defined on the cmdline.
        image: registry.local:5000/fibonacci-webservice:{{ fibonacci_webservice_version }}
        state: started
        restart_policy: unless-stopped
        detach: true
        published_ports:
          - "{{ webservice_host_port }}:27372"
        env:
          API_URL: "http://{{ ansible_host }}:{{ webservice_host_port }}"
